In [22]:
import pandas as pd

In [23]:
df = pd.read_csv('indian_bus_fare_dataset.csv')

In [24]:
df.shape

(500000, 8)

In [25]:
df.sample(5)

,Agency,Source,Destination,Bus Type,Travel Date,Fare Price (INR),Total Seats,Duration (hours)
437042,SRS Travels,Bangalore,Delhi,Volvo,2017-01-23,2690.31,49,6.4
312223,Parveen Travels,Lucknow,Pune,Volvo,2019-06-28,885.73,50,11.4
476984,KPN Travels,Mumbai,Chennai,Luxury,2018-11-12,1530.06,46,17.9
473485,RedBus,Mumbai,Ahmedabad,AC Seater,2017-01-03,1227.75,45,9.1
5309,Sharma Travels,Jaipur,Mumbai,AC Seater,2022-06-27,2623.53,31,9.8

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Agency            500000 non-null  object
 1   Source            500000 non-null  object
 2   Destination       500000 non-null  object
 3   Bus Type          500000 non-null  object
 4   Travel Date       500000 non-null  object
 5   Fare Price (INR)  500000 non-null  float64
 6   Total Seats       500000 non-null  int64
 7   Duration (hours)  500000 non-null  float64
dtypes: float64(2), int64(1), object(5)
memory usage: 30.5+ MB

In [27]:
df.isnull().sum()

Agency              0
Source              0
Destination         0
Bus Type            0
Travel Date         0
Fare Price (INR)    0
Total Seats         0
Duration (hours)    0
dtype: int64

In [28]:
df.describe()

       Fare Price (INR)    Total Seats  Duration (hours)
count     500000.000000  500000.000000     500000.000000
mean        1609.126981      35.013980         11.492154
std          772.660011       8.938075          3.750610
min          271.000000      20.000000          5.000000
25%          959.897500      27.000000          8.200000
50%         1575.470000      35.000000         11.500000
75%         2195.190000      43.000000         14.700000
max         3747.760000      50.000000         18.000000

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df.corr(numeric_only=True)['Total Seats']

Fare Price (INR)    0.002829
Total Seats         1.000000
Duration (hours)    0.001501
Name: Total Seats, dtype: float64