In [ ]:
import pandas as pd

In [ ]:
countries_series = pd.read_json('countries.json')
countries_df = pd.json_normalize(countries_series['countries'])

In [ ]:
display(countries_df)

                    name code           capital    region  population currency
0            Afghanistan   AF             Kabul      Asia    38928346      AFN
1                Albania   AL            Tirana    Europe     2877797      ALL
2                Algeria   DZ           Algiers    Africa    43851044      DZD
3              Argentina   AR      Buenos Aires  Americas    45195774      ARS
4              Australia   AU          Canberra   Oceania    25499884      AUD
5                Austria   AT            Vienna    Europe     9006398      EUR
6                Belgium   BE          Brussels    Europe    11589623      EUR
7                 Brazil   BR          Brasília  Americas   212559417      BRL
8                 Canada   CA            Ottawa  Americas    37742154      CAD
9                  Chile   CL          Santiago  Americas    19116201      CLP
10                 China   CN           Beijing      Asia  1439323776      CNY
11              Colombia   CO            Bogotá  Americas    50882891      COP
12        Czech Republic   CZ            Prague    Europe    10708981      CZK
13               Denmark   DK        Copenhagen    Europe     5792202      DKK
14                 Egypt   EG             Cairo    Africa   102334404      EGP
15               Finland   FI          Helsinki    Europe     5540720      EUR
16                France   FR             Paris    Europe    65273511      EUR
17               Germany   DE            Berlin    Europe    83783942      EUR
18                Greece   GR            Athens    Europe    10423054      EUR
19                 India   IN         New Delhi      Asia  1380004385      INR
20             Indonesia   ID           Jakarta      Asia   273523615      IDR
21               Ireland   IE            Dublin    Europe     4937786      EUR
22                Israel   IL         Jerusalem      Asia     8655535      ILS
23                 Italy   IT              Rome    Europe    60461826      EUR
24                 Japan   JP             Tokyo      Asia   126476461      JPY
25                 Kenya   KE           Nairobi    Africa    53771296      KES
26              Malaysia   MY      Kuala Lumpur      Asia    32365999      MYR
27                Mexico   MX       Mexico City  Americas   128932753      MXN
28           Netherlands   NL         Amsterdam    Europe    17134872      EUR
29           New Zealand   NZ        Wellington   Oceania     4822233      NZD
30               Nigeria   NG             Abuja    Africa   206139589      NGN
31                Norway   NO              Oslo    Europe     5421241      NOK
32              Pakistan   PK         Islamabad      Asia   220892340      PKR
33           Philippines   PH            Manila      Asia   109581078      PHP
34                Poland   PL            Warsaw    Europe    37846611      PLN
35              Portugal   PT            Lisbon    Europe    10196709      EUR
36                Russia   RU            Moscow    Europe   145934462      RUB
37          Saudi Arabia   SA            Riyadh      Asia    34813871      SAR
38             Singapore   SG         Singapore      Asia     5850342      SGD
39          South Africa   ZA          Pretoria    Africa    59308690      ZAR
40           South Korea   KR             Seoul      Asia    51269185      KRW
41                 Spain   ES            Madrid    Europe    46754778      EUR
42                Sweden   SE         Stockholm    Europe    10099265      SEK
43           Switzerland   CH              Bern    Europe     8654622      CHF
44              Thailand   TH           Bangkok      Asia    69799978      THB
45                Turkey   TR            Ankara      Asia    84339067      TRY
46               Ukraine   UA              Kyiv    Europe    43733762      UAH
47  United Arab Emirates   AE         Abu Dhabi      Asia     9890402      AED
48        United Kingdom   GB            London    Europe    67886011      GBP
49         United States   US  Washington, D.C.  Americas   331002651      USD
50               Vietnam   VN             Hanoi      Asia    97338579      VND

In [ ]:
exchange_rates_df = pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')
display(exchange_rates_df.head())

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-06,1775433602,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-06,1775433602,0.0394
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-06,1775433602,0.6900
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-06,1775433602,0.8960
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-06,1775433602,4.0700

In [ ]:
!pip install ipython-sql
%load_ext sql
%sql sqlite:///world.db

Requirement already satisfied: ipython-sql in /usr/local/lib/python3.12/dist-packages (0.5.0)
Requirement already satisfied: prettytable in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (3.17.0)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (7.34.0)
Requirement already satisfied: sqlalchemy>=2.0 in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (2.0.48)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=2.0->ipython-sql) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (75.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (2.20.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable->ipython-sql) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [ ]:
%%sql
CREATE TABLE countrylanguage (
    CountryCode TEXT,
    Language TEXT,
    IsOfficial TEXT,
    Percentage REAL
);

 * sqlite:///world.db
(sqlite3.OperationalError) table countrylanguage already exists
[SQL: CREATE TABLE countrylanguage (
    CountryCode TEXT,
    Language TEXT,
    IsOfficial TEXT,
    Percentage REAL
);]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [ ]:
%%sql
INSERT INTO countrylanguage VALUES
('IND','Hindi','T',40.0),
('USA','English','T',95.0);

 * sqlite:///world.db
2 rows affected.

[]

In [ ]:
%config SqlMagic.style = 'PLAIN_COLUMNS'